"""empty message

Revision ID: 330d5a22f2f7
Revises: 34708ece4349
Create Date: 2020-05-24 22:34:30.537114

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '330d5a22f2f7'
down_revision = '34708ece4349'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('problem', 'test')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('problem', sa.Column('test', sa.VARCHAR(), autoincrement=False, nullable=True))
    # ### end Alembic commands ###
