"""empty message

Revision ID: 34708ece4349
Revises: 
Create Date: 2020-05-24 22:34:04.948108

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '34708ece4349'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('problem', sa.Column('test', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('problem', 'test')
    # ### end Alembic commands ###
